repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: gofmt
        entry: gofmt -w ./cmd ./internal
        language: system
        types: [go]
        pass_filenames: false
      - id: go-test
        name: go test
        entry: go test -count=1 ./...
        language: system
        pass_filenames: false
        always_run: true
