// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {downloader} from '../models';
import {context} from '../models';

export function AddToQueue(arg1:app.ConfigDTO):Promise<app.QueueTaskDTO>;

export function ApplyPreset(arg1:string):Promise<app.ConfigDTO>;

export function CancelQueueTask(arg1:string):Promise<boolean>;

export function CancelScheduledQueueRun():Promise<void>;

export function CheckAppUpdate():Promise<app.AppUpdateDTO>;

export function CheckDependencies():Promise<Array<app.DependencyDTO>>;

export function CheckInstallGuard(arg1:string):Promise<app.InstallGuardDTO>;

export function ClearHistory():Promise<void>;

export function ClearQueue():Promise<void>;

export function CloseIdleInstances():Promise<number>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportSettings(arg1:string):Promise<void>;

export function GetHistory():Promise<Array<app.HistoryItemDTO>>;

export function GetLocales(arg1:string):Promise<Record<string, string>>;

export function GetMergeFormats():Promise<Array<string>>;

export function GetPresets():Promise<Array<string>>;

export function GetQualityPresets():Promise<Array<Record<string, string>>>;

export function GetScheduledQueueRun():Promise<number>;

export function GetState():Promise<app.AppStateDTO>;

export function HealthCheck():Promise<Array<app.HealthIssueDTO>>;

export function ImportSettings(arg1:string):Promise<void>;

export function InstallDependency(arg1:string):Promise<string>;

export function KillInstance(arg1:number):Promise<void>;

export function ListOtherInstances():Promise<Array<app.InstanceDTO>>;

export function ListProfiles():Promise<Array<string>>;

export function LoadProfile(arg1:string):Promise<app.ProfileDTO>;

export function LoadSession(arg1:string):Promise<app.ConfigDTO>;

export function MoveQueueItem(arg1:string,arg2:number):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseQueueTask(arg1:string):Promise<void>;

export function PickFile():Promise<string>;

export function PickFolder():Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function PreviewCommand(arg1:app.ConfigDTO):Promise<string>;

export function ProbeFormats(arg1:app.ConfigDTO):Promise<downloader.ProbeResult>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ReorderQueue(arg1:Array<string>):Promise<void>;

export function ResolveDependenciesLocal():Promise<Array<app.DependencyDTO>>;

export function ResumeQueueTask(arg1:string):Promise<void>;

export function ResumeSession(arg1:string):Promise<app.ConfigDTO>;

export function RetryFailedQueue():Promise<void>;

export function RunDownload(arg1:app.ConfigDTO):Promise<void>;

export function RunQueue():Promise<void>;

export function SaveProfile(arg1:app.ProfileDTO):Promise<void>;

export function SaveSession(arg1:string):Promise<void>;

export function SaveSettings(arg1:app.AppSettingsDTO):Promise<void>;

export function ScheduleQueueRun(arg1:number):Promise<void>;

export function ShouldQuit():Promise<boolean>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StopDownload():Promise<void>;

export function UpdateDependency(arg1:string):Promise<string>;

export function UpdateQueueTask(arg1:string,arg2:app.ConfigDTO):Promise<void>;
