// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['app']['App']['AddToQueue'](arg1);
}

export function ApplyPreset(arg1) {
  return window['go']['app']['App']['ApplyPreset'](arg1);
}

export function CancelQueueTask(arg1) {
  return window['go']['app']['App']['CancelQueueTask'](arg1);
}

export function CancelScheduledQueueRun() {
  return window['go']['app']['App']['CancelScheduledQueueRun']();
}

export function CheckAppUpdate() {
  return window['go']['app']['App']['CheckAppUpdate']();
}

export function CheckDependencies() {
  return window['go']['app']['App']['CheckDependencies']();
}

export function CheckInstallGuard(arg1) {
  return window['go']['app']['App']['CheckInstallGuard'](arg1);
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function ClearQueue() {
  return window['go']['app']['App']['ClearQueue']();
}

export function CloseIdleInstances() {
  return window['go']['app']['App']['CloseIdleInstances']();
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function ExportSettings(arg1) {
  return window['go']['app']['App']['ExportSettings'](arg1);
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}

export function GetLocales(arg1) {
  return window['go']['app']['App']['GetLocales'](arg1);
}

export function GetMergeFormats() {
  return window['go']['app']['App']['GetMergeFormats']();
}

export function GetPresets() {
  return window['go']['app']['App']['GetPresets']();
}

export function GetQualityPresets() {
  return window['go']['app']['App']['GetQualityPresets']();
}

export function GetScheduledQueueRun() {
  return window['go']['app']['App']['GetScheduledQueueRun']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function HealthCheck() {
  return window['go']['app']['App']['HealthCheck']();
}

export function ImportSettings(arg1) {
  return window['go']['app']['App']['ImportSettings'](arg1);
}

export function InstallDependency(arg1) {
  return window['go']['app']['App']['InstallDependency'](arg1);
}

export function KillInstance(arg1) {
  return window['go']['app']['App']['KillInstance'](arg1);
}

export function ListOtherInstances() {
  return window['go']['app']['App']['ListOtherInstances']();
}

export function ListProfiles() {
  return window['go']['app']['App']['ListProfiles']();
}

export function LoadProfile(arg1) {
  return window['go']['app']['App']['LoadProfile'](arg1);
}

export function LoadSession(arg1) {
  return window['go']['app']['App']['LoadSession'](arg1);
}

export function MoveQueueItem(arg1, arg2) {
  return window['go']['app']['App']['MoveQueueItem'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function PauseQueueTask(arg1) {
  return window['go']['app']['App']['PauseQueueTask'](arg1);
}

export function PickFile() {
  return window['go']['app']['App']['PickFile']();
}

export function PickFolder() {
  return window['go']['app']['App']['PickFolder']();
}

export function PickSaveFile(arg1) {
  return window['go']['app']['App']['PickSaveFile'](arg1);
}

export function PreviewCommand(arg1) {
  return window['go']['app']['App']['PreviewCommand'](arg1);
}

export function ProbeFormats(arg1) {
  return window['go']['app']['App']['ProbeFormats'](arg1);
}

export function RemoveFromQueue(arg1) {
  return window['go']['app']['App']['RemoveFromQueue'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['app']['App']['RenameProfile'](arg1, arg2);
}

export function ReorderQueue(arg1) {
  return window['go']['app']['App']['ReorderQueue'](arg1);
}

export function ResolveDependenciesLocal() {
  return window['go']['app']['App']['ResolveDependenciesLocal']();
}

export function ResumeQueueTask(arg1) {
  return window['go']['app']['App']['ResumeQueueTask'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['app']['App']['ResumeSession'](arg1);
}

export function RetryFailedQueue() {
  return window['go']['app']['App']['RetryFailedQueue']();
}

export function RunDownload(arg1) {
  return window['go']['app']['App']['RunDownload'](arg1);
}

export function RunQueue() {
  return window['go']['app']['App']['RunQueue']();
}

export function SaveProfile(arg1) {
  return window['go']['app']['App']['SaveProfile'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function ScheduleQueueRun(arg1) {
  return window['go']['app']['App']['ScheduleQueueRun'](arg1);
}

export function ShouldQuit() {
  return window['go']['app']['App']['ShouldQuit']();
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StopDownload() {
  return window['go']['app']['App']['StopDownload']();
}

export function UpdateDependency(arg1) {
  return window['go']['app']['App']['UpdateDependency'](arg1);
}

export function UpdateQueueTask(arg1, arg2) {
  return window['go']['app']['App']['UpdateQueueTask'](arg1, arg2);
}
